config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get 'dashboard' => 'pages#dashboard'

  resources :tools do
    resources :bookings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tool
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user

  has_many :bookings
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :tools
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_tool, only: %i[new create]
  before_action :set_booking, only: %i[edit update]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.tool = @tool
    @booking.user = current_user
    @booking.status = "pending"
    if @tool.user == current_user
      redirect_to tools_path, alert: "You cannot book your own tool!"
    elsif @booking.save
      redirect_to tools_path, notice: "booked!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    # @booking.status = booking_params[:accept] == 'true' ? 'accepted' : 'rejected'

    if booking_params[:accept] == 'true'
      @booking.status = 'accepted'
    elsif booking_params[:accept] == 'false'
      @booking.status = 'rejected'
    end

    if @booking.save
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def set_tool
    @tool = Tool.find(params[:tool_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :accept)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home


  def dashboard
    @bookings_from_other_users = current_user.tools.flat_map { |tool| tool.bookings }
    @my_bookings = Booking.where(user: current_user)
  end

  def home
    if params[:query].present?
      sql_subquery = "name ILIKE :query"
      @tools = Tool.where(sql_subquery, query: "%#{params[:query]}%")
    else
      @tools = Tool.all
    end
  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    if @tool.save
      redirect_to tool_path(@tool)
    else
      render :new
    end
  end

  def index
    if params[:query].present?
      sql_subquery = "name ILIKE :query"
      @tools = Tool.where(sql_subquery, query: "%#{params[:query]}%")
    else
      @tools = Tool.all
    end
    @markers = @tools.geocoded.map do |tool|
      {
        lat: tool.latitude,
        lng: tool.longitude
      }
    end
  end




  def show
    @tool = Tool.find(params[:id])
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :detail, :price, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Edit Booking for </h1>

<%= form_with(model: @booking) do |form| %>
  <div>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :status %>
  </div>

  <%= form.submit %>
<% end %>

<%= link_to 'Back', tool_path(@booking.tool) %>

app/views/bookings/new.html.erb
<h1>New Booking for </h1>

<%= simple_form_for([@tool, @booking]) do |form| %>
  <div>
    <%= form.input :start_date %>
  </div>

  <div>
    <%= form.input :end_date %>
  </div>


  <%= form.submit %>
<% end %>

<%= link_to 'Back', tool_path(@tool) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTool</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <%= favicon_link_tag 'favicon.ico' %>

  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container mt-4">
  <h1 class="text-center mb-4">Bookings</h1>

  <h2 class="mb-3">Mes locations</h2>
  <div class="row">
    <% @bookings_from_other_users.each do |booking| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100 shadow">
          <div class="card-body">
            <h5 class="card-title"><%= booking.tool.name %></h5>
            <p class="card-text"><strong>User:</strong> <%= booking.user.email %></p>
            <p class="card-text"><strong>Start Date:</strong> <%= booking.start_date %></p>
            <p class="card-text"><strong>End Date:</strong> <%= booking.end_date %></p>
            <p class="card-text"><strong>Status:</strong> <%= booking.status %></p>

            <div class="d-flex justify-content-between">
              <%= simple_form_for([booking.tool, booking], method: :patch, html: { class: 'w-50 mr-2' }) do |f| %>
                <%= f.hidden_field :accept, value: true %>
                <%= f.submit 'Accept', class: 'btn btn-success btn-block' %>
              <% end %>

              <%= simple_form_for([booking.tool, booking], method: :patch, html: { class: 'w-50' }) do |f| %>
                <%= f.hidden_field :accept, value: false %>
                <%= f.submit 'Decline', class: 'btn btn-danger btn-block' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <h2 class="my-3">Mes reservations</h2>
  <div class="row">
    <% @my_bookings.each do |booking| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100 shadow">
          <div class="card-body">
            <h5 class="card-title"><%= booking.tool.name %></h5>
            <p class="card-text"><strong>Start Date:</strong> <%= booking.start_date %></p>
            <p class="card-text"><strong>End Date:</strong> <%= booking.end_date %></p>
            <p class="card-text"><strong>Status:</strong> <%= booking.status %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid p-0 banner" style="background: url('<%= image_path "banner.png" %>'); background-size: 100% auto; background-repeat: no-repeat; background-position: center; height: 70vh;">
  <div class="d-flex justify-content-center align-items-end h-100">
    <div class="text-center text-white" style="margin-bottom: 50px;">
      <h1 class="display-4 font-weight-bold">Bienvenue sur My Tool</h1>
      <p class="lead custom-icon-color">La plateforme de location d'outils entre particuliers</p>
      <%= form_with url: tools_path, method: :get, class: "d-flex justify-content-center mt-4" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control col-sm-6",
              placeholder: "Trouver un outil"
          %>
        <%= submit_tag "Rechercher", name: "", class: "btn btn-primary ml-2" %>
      <% end %>
    </div>
  </div>
</div>


<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-lg-8 text-center">
      <h2 class="display-4">Comment ça marche ?</h2>
      <p class="lead mt-4">My Tool est une plateforme numérique dédiée à l'échange et la location d'outils entre particuliers. Que vous soyez un bricoleur occasionnel ou un professionnel, notre plateforme vous met en relation avec les personnes possédant les outils dont vous avez besoin.</p>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-lg-4 text-center">
      <i class="fas fa-search fa-3x"></i>
      <h4 class="mt-4">Trouvez l'outil qu'il vous faut</h4>
      <p>Parcourez une vaste sélection d'outils proposés par des vendeurs locaux. Qu'il s'agisse de matériel de jardinage ou d'outils de construction, vous trouverez ce qu'il vous faut pour vos projets à venir.</p>
    </div>
    <div class="col-lg-4 text-center">
      <i class="fas fa-handshake fa-3x"></i>
      <h4 class="mt-4">Contactez le propriétaire</h4>
      <p>Une fois que vous avez trouvé l'outil que vous cherchez, prenez contact avec le propriétaire pour convenir des modalités de location.</p>
    </div>
    <div class="col-lg-4 text-center">
      <i class="fas fa-tools fa-3x"></i>
      <h4 class="mt-4">Commencez à bricoler !</h4>
      <p>Une fois l'outil en main, il ne vous reste plus qu'à commencer vos travaux. Simple, économique et convivial !</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light sticky-top navbar-lewagon">
  <div class="container-fluid navbar-width-80">
    <%= link_to "/", class: "navbar-brand" do %>
            <%= image_tag "logo.png" %>
            <span class="brand-font"><%= "My Tool" %></span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "/tools/new", class: "nav-link" do %>
              <i class="bi bi-tools custom-icon-color"></i> Déposer une annonce
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Mon compte", "/dashboard", class: "nav-link text-white btn btn-primary custom-button" %>
          </li>
          <li class="nav-item dropdown ">
         <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <%= current_user.photo.key != nil ? image_tag(current_user.photo, class: "avatar", alt: "dropdown menu") : image_tag("logo.png", class: "avatar", alt: "dropdown menu") %>
</a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="bi bi-person custom-icon-color"></i> Me connecter
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tools/_form.html.erb
<%= simple_form_for(tool) do |f|%>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
<% end %>

app/views/tools/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-12 col-md-6">
      <%= form_with url: tools_path, method: :get, class: "d-flex justify-content-center" do %>
       <%= text_field_tag :query,
          params[:query],
          class: "form-control me-2",
          placeholder: "Find a tool",
          style: "background-color: white;"
        %>
        <button class="btn btn-primary" type="submit">Search</button>
      <% end %>
    </div>
  </div>


  <div class="row">
    <div class="col-md-6">
      <% @tools.each_slice(2) do |tool_slice| %>
        <div class="row justify-content-center">
          <% tool_slice.each do |tool| %>
            <div class="col-md-6 mb-4">
              <div class="card h-100 shadow-lg">
                <% if tool.photos.attached? && tool.photos.any? %>
                  <%= image_tag tool.photos.first, size: "200x200", class: "card-img-top rounded", alt: "tool image", style: 'width: 100%; object-fit: cover;' %>
                <% else %>
                  <%= image_tag("banner.png", size: "200x200", class: "card-img-top rounded", alt: "tool image", style: 'object-fit: cover;') %>
                <% end %>
                <div class="card-body text-center">
                  <%= link_to tool_path(tool), class: "text-decoration-none" do %>
                    <h5 class="card-title fw-bold text-primary"><%= tool.name %></h5>
                  <% end %>
                  <p class="card-text"><small class="text-muted">Loué par: </small><%= tool.user.email %></p>
                  <p class="card-text"><small class="text-muted">Adresse: </small><%= tool.user.address %></p>
                  <p class="card-text"><small class="text-muted">Prix: </small><%= tool.price %>€</p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

    </div>

    <div class="col-md-6">
      <div class="sticky-container" style="width: 100%; height: 100vh;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>

app/views/tools/new.html.erb
<div class="container my-5">
  <h2 class="text-center mb-5">Add a New Tool</h2>

  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="card shadow">
        <div class="card-body">
          <%= form_with(model: @tool, url: tools_path, local: true, class: "new-tool-form") do |f| %>

            <div class="mb-4">
              <%= f.label :name, class: 'form-label' %>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon1"><i class="fas fa-toolbox custom-icon-color"></i></span>
                <%= f.text_field :name, class: 'form-control', placeholder: "Tool's name" %>
              </div>
            </div>


            <div class="mb-4">
              <%= f.label :detail, class: 'form-label' %>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon2"><i class="fas fa-info-circle custom-icon-color"></i></span>
                <%= f.text_field :detail, class: 'form-control', placeholder: "More details" %>
              </div>
            </div>

            <div class="mb-4">
              <%= f.label :price, class: 'form-label' %>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon3"><i class="fas fa-dollar-sign custom-icon-color"></i></span>
                <%= f.number_field :price, class: 'form-control', placeholder: "Price" %>
              </div>
            </div>

            <div class="actions text-center">
              <%= f.submit "Create Tool", class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="text-center mt-3">
    <%= link_to 'Back', tools_path, class: 'btn btn-dark' %>
  </div>
</div>

app/views/tools/show.html.erb
<div class="container mt-4">
    <h1 class="text-center mb-4">Tool Details</h1>

    <div class="card w-75 mx-auto mb-4">
        <div class="row">
            <div class="col-md-6">
                <div class="card-body">
                    <h5 class="card-title"><%= @tool.name %></h5>
                    <p class="card-text"><%= @tool.detail %></p>
                    <p class="card-text">Price: <%= @tool.price %></p>
                </div>
            </div>
            <div class="col-md-6">
                <% if @tool.photos.any? %>
                    <%= cl_image_tag @tool.photos.first.key, height: 300, width: 400, crop: :fill, class: 'img-thumbnail' %>
                    <% else %>
                    <%= image_tag "banner.png", height: 300, width: 400, crop: :fill, class: 'img-thumbnail' %>
                <% end %>
            </div>
        </div>
        <div class="card-footer text-center">
            <%= link_to 'Reserve this Tool', new_tool_booking_path(@tool), class: 'btn btn-primary mt-3 me-2' %>
        </div>
        </div>
          <div class="text-center mt-3">
    <%= link_to 'Back', tools_path, class: 'btn btn-dark' %>
  </div>
</div>


    <div class="row justify-content-center mb-4">
        <% @tool.photos.drop(1).each do |photo| %>
            <div class="col-md-4 mb-3">
                <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill, class: 'img-thumbnail' %>
            </div>
        <% end %>
    </div>
</div>